nldate = {'jan': '01',
          'feb': '02',
          'mrt': '03',
          'apr': '04',
          'mei': '05',
          'jun': '06',
          'jul': '07',
          'aug': '08',
          'sep': '09',
          'okt': '10',
          'nov': '11',
          "dec": '12'}

match = {1: 'Januari',
         2: 'Februari',
         3: 'Maart',
         4: 'April',
         5: 'Mei',
         6: 'Juni',
         7: 'Juli',
         8: 'Augustus',
         9: 'September',
         10: 'Oktober',
         11: 'November',
         12: 'December'}
